services:
  mcp-video-transcriber:
    build: .
    container_name: mcp-video-transcriber
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Server configuration
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Persistent database storage
      - ./data:/app/data
      # Optional: Mount logs directory
      - ./logs:/app/logs
    # Health check to ensure service is running
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - frontend
      - mcp_network

  nginx:
    image: nginx:latest
    container_name: mcp_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mcp-video-transcriber
    networks:
      - frontend
      - mcp_network

networks:
  mcp_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  frontend:
    external: true
    name: nginx-proxy
