[project]
name = "mcp-video-transcriber"
version = "0.1.0"
description = "MCP server for transcribing videos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.5",
]
